### PR TITLE
Github workflows init

### PR DESCRIPTION
**Pull request by StanleyXie-otto**
Create github workflow yaml files

### CODE REVIEW

**Review by StanleyXie — APPROVED** [review]
LGTM

**Review by StanleyXie — APPROVED** [review]
LGTM

**Review by StanleyXie — APPROVED** [review]
Approve agian

**Review by StanleyXie — APPROVED** [review]

**Review by StanleyXie — APPROVED** [review]
LGTM Again

**Comment by StanleyXie-otto** [comment]
Try test again

**Pull request closed without merging**
